### ISSUE TITLE
Slidedeck "Estratégias de deploy do Istio com Golang" apresenta 404

### ISSUE THREAD

**Issue by Streppel** [gopherconbr/2019-talks#1]
O link do slidedeck para a palestra 
11:05 | Victor Santos | Estratégias de deploy do Istio com Golang
está retornando 404

O link é [https://github.com/gopherconbr/2019-talks/blob/master/vsantos.github.io/gophercon](https://github.com/gopherconbr/2019-talks/blob/master/vsantos.github.io/gophercon)

**Comment by guilhermebr** [comment]
@Streppel thanks!
